version: '2'
services:
  #data:
  #  image: busybox
  #  volumes:
  #   - ./app:/var/www/html
  #  tty: true

  data:
    build:
      context: ./.docker
      dockerfile: Dockerfile-www
    volumes:
     - ./seed/conf:/var/www/html/conf
     - ./seed/data:/var/www/html/data
    tty: true

  php:
    build: 
      context: ./.docker
      dockerfile: Dockerfile-php
    volumes_from:
     - data
    volumes:
     - ./php.ini:/usr/local/etc/php/php.ini
     - ./php.cron:/etc/cron.d/seeddms-cron
    links:
     - db

  web:
    image: nginx
    ports:
     - "5080:80"
    volumes_from:
     - data
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
     - php

  db:
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=234sdf2j3fsdf34r234
      - MYSQL_DATABASE=seeddms
      - MYSQL_USER=seeddms
      - MYSQL_PASSWORD=3jKsdfsfJfd84hjs
